import Navbar from './components/Navbar';
import Navbutton from './components/Navbutton';
import './globals.scss';

import { NextAuthProvider } from './components/Nextauthprovider';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
	title: "The Journey's Middle",
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="theme-dark">
				<NextAuthProvider refetchOnWindowFocus={false}>
					<div id="head">
						<h1 id="mainHeading">The Journey's Middle</h1>
						<h4 id="subHeading">Let's meet in the Middle</h4>
					</div>
					<Navbar />
					<Navbutton />
					<main className="flex min-h-screen flex-col items-center p-6">
						{children}
					</main>
				</NextAuthProvider>
			</body>
		</html>
	);
}
